#!/usr/bin/env bash

# Run all the steps in a one or more stages
# Usage: 
#   run_BPS O_DrawDepth P_DrawAnnotation ...

start_time=`date +%s`

function run_stage {
    DIR=$1
    pushd $DIR

        CONFIG="BPS_Stage.config"
        if ! [ -f $CONFIG ]; then
            echo $DIR/$CONFIG does not exist! Exiting.
        fi

        source ./$CONFIG
        # All steps are now specified in $STEPS
        
        # TODO: step scripts should indicate whether they exited successfully or not with a return status.
        # Then we should stop if an error is detected
        for step in $STEPS; do
            echo running $step
            sh $step
        done

    popd
}

if [ -z $1 ]; then
    echo Target is not specified.  Exiting.
    exit
fi

for DIR in $@; do

    if ! [ -d $DIR ]; then
        echo Target $DIR unknown.  Exiting.
        exit
    fi

    echo Processing $DIR
    run_stage $DIR
done

end_time=`date +%s`

echo Total execution time: `expr $end_time - $start_time` seconds.
